
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
   
spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
      - id: cropService
        uri: http://localhost:8086/
        predicates:
        - Path=/api/**

      - id: cartService
        uri: http://localhost:8090/
        predicates:
        - Path=/apicart/**

        
          